apiVersion: apps/v1
kind: Deployment
metadata:
  name: pla-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pla-api-gateway
  template:
    metadata:
      labels:
        app: pla-api-gateway
    spec:
      containers:
        - image: docker.io/ssbansal/pl-aggregator:latest
          imagePullPolicy: Always
          name: pla-api-gateway-container
          workingDir: /app
          command: [dotnet, NBS.CRE.APIGateway.dll]
          ports:
             - containerPort: 80
          env:
            - name: UI_HOST
              value: "0.0.0.0"
            - name: UI_PORT
              value: "80"
            - name: RMQ_HOST
              value: "rabbitmq"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pla-policy-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pla-policy-checker
  template:
    metadata:
      labels:
        app: pla-policy-checker
    spec:
      containers:
        - image: docker.io/ssbansal/pl-aggregator:latest
          imagePullPolicy: Always
          name: pla-policy-checker-container
          workingDir: /app
          command: [dotnet, NBS.CRE.PolicyChecker.dll]
          env:
            - name: RMQ_HOST
              value: "rabbitmq"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pla-soft-quote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pla-soft-quote
  template:
    metadata:
      labels:
        app: pla-soft-quote
    spec:
      containers:
        - image: docker.io/ssbansal/pl-aggregator:latest
          imagePullPolicy: Always
          name: pla-soft-quote-container
          workingDir: /app
          command: [dotnet, NBS.CRE.SoftQuote.dll]
          env:
            - name: RMQ_HOST
              value: "rabbitmq"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pla-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pla-rabbitmq
  template:
    metadata:
      labels:
        app: pla-rabbitmq
    spec:
      containers:
        - image: docker.io/rabbitmq:latest
          name: pla-rabbitmq-container
          ports:
             - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: pla-rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672