apiVersion: apps/v1
kind: Deployment
metadata:
  name: pla-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pla-api-gateway
  template:
    metadata:
      labels:
        app: pla-api-gateway
    spec:
      containers:
        - image: docker.io/ssbansal/pl-aggregator:latest
          name: pla-api-gateway-container
          workingDir: /app
          command: [dotnet, NBS.CRE.APIGateway.dll]
          ports:
             - containerPort: 80
          env:
            - name: UI_HOST
              value: "0.0.0.0"
            - name: UI_PORT
              value: "80"